-- V10: Audit event log for compliance and observability.

CREATE TABLE IF NOT EXISTS audit_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type       VARCHAR(60)  NOT NULL,
    actor_user_id    BIGINT,
    target_entity    VARCHAR(60),
    target_id        VARCHAR(40),
    ip_address       VARCHAR(45),
    correlation_id   VARCHAR(36),
    description      VARCHAR(500),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_events_actor
        FOREIGN KEY (actor_user_id)
        REFERENCES app_users (id)
        ON DELETE SET NULL
);

CREATE INDEX idx_audit_events_actor_user_id ON audit_events (actor_user_id);
CREATE INDEX idx_audit_events_event_type    ON audit_events (event_type);
CREATE INDEX idx_audit_events_created_at    ON audit_events (created_at DESC);
