CREATE TABLE IF NOT EXISTS claims (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_number VARCHAR(80) NOT NULL,
    patient_control_number VARCHAR(80),
    payer_name VARCHAR(255) NOT NULL,
    provider_name VARCHAR(255) NOT NULL,
    service_date DATE NOT NULL,
    billed_amount DECIMAL(12, 2) NOT NULL,
    claim_status VARCHAR(50) NOT NULL,
    claim_notes VARCHAR(2000),
    created_by_user_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_claims_created_by_user
        FOREIGN KEY (created_by_user_id)
        REFERENCES app_users (id)
);

CREATE INDEX IF NOT EXISTS idx_claims_created_by_user_id
    ON claims (created_by_user_id);

CREATE INDEX IF NOT EXISTS idx_claims_created_by_user_created_at
    ON claims (created_by_user_id, created_at);
