CREATE TABLE IF NOT EXISTS claim_review_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL,
    author_user_id BIGINT NOT NULL,
    note_text VARCHAR(2000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_claim_review_notes_claim
        FOREIGN KEY (claim_id)
        REFERENCES claims (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_claim_review_notes_author_user
        FOREIGN KEY (author_user_id)
        REFERENCES app_users (id)
);

CREATE INDEX IF NOT EXISTS idx_claim_review_notes_claim_id
    ON claim_review_notes (claim_id);

CREATE INDEX IF NOT EXISTS idx_claim_review_notes_author_user_id
    ON claim_review_notes (author_user_id);

CREATE INDEX IF NOT EXISTS idx_claim_review_notes_claim_created_at
    ON claim_review_notes (claim_id, created_at);
