ALTER TABLE claims
    ADD COLUMN IF NOT EXISTS prior_auth_required BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE claims
    ADD COLUMN IF NOT EXISTS prior_auth_number VARCHAR(80);

CREATE TABLE IF NOT EXISTS claim_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id BIGINT NOT NULL,
    risk_score INTEGER NOT NULL,
    risk_category VARCHAR(20) NOT NULL,
    primary_risk_reason VARCHAR(500) NOT NULL,
    ai_summary VARCHAR(2000) NOT NULL,
    recommended_actions VARCHAR(2000) NOT NULL,
    human_review_required BOOLEAN NOT NULL,
    fallback_used BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_claim_analyses_claim
        FOREIGN KEY (claim_id)
        REFERENCES claims (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_claim_analyses_claim_id
    ON claim_analyses (claim_id);

CREATE INDEX IF NOT EXISTS idx_claim_analyses_claim_created_at
    ON claim_analyses (claim_id, created_at);

CREATE TABLE IF NOT EXISTS claim_analysis_findings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id BIGINT NOT NULL,
    finding_code VARCHAR(80) NOT NULL,
    description VARCHAR(500) NOT NULL,
    points INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_claim_analysis_findings_analysis
        FOREIGN KEY (analysis_id)
        REFERENCES claim_analyses (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_claim_analysis_findings_analysis_id
    ON claim_analysis_findings (analysis_id);
